[package]
name = "tac0"
version = "0.1.0"
edition = "2024"
build = "build.rs"

# The generated code depends on lalrpop-util.
[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.22.1"

[dependencies]
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }

