; This grammar represents a subset of C. This is a work in progress and is not complete. 
; It covers the basic syntax of C, but does not cover all of the features of C.

<program> ::= E | <global_unit>
<global_unit> ::= <function>
				| <struct>
                | <typedef>
                | <header_import>

<header_import> ::= "#include" "<" <ident> ".h" ">"
                | "#include" "\"" <ident> ".h" "\""
                
<typ> ::= "void"
		| "int"
        | "char"
        | "double"
		| "long"
        | "short"
        | "signed"
        | "unsigned"
        | <struct_ident>
        | <ident>
        
<function> ::= <typ> <ident> "(" <param_list> ")" ";"
			| <typ> <ident> "(" <param_list> ")" "{" <compound_statement> "}"

            
<typedef> ::= "typedef" <typ> <ident> ";"

<compound_statement> ::= "{" <statement_list> "}"

<statement_list> ::= E | <statement> <statement_list>

; ---- Statements ----
<statement> ::= <open_statement>
            | <closed_statement>

<open_statement> ::= "if" "(" <expression> ")" <closed_statement>
                | "if" "(" <expression> ")" <open_statement>
                | "if" "(" <expression> ")" <closed_statement> "else" <open_statement>
                | "while" "(" <expression> ")" <open_statement>
                | "for" "(" <expression> ";" <expression> ";" <expression> ")" <open_statement>

<closed_statement> ::= <non_control_statement>
                    | "if" "(" <expression> ")" <closed_statement> "else" <closed_statement>
                    | "while" "(" <expression> ")" <closed_statement>
                    | "for" "(" <expression> ";" <expression> ";" <expression> ")" <closed_statement>

<non_control_statement> ::= <simple_statement> ";"
                    | <compound_statement>
                    | "return" <expression> ";"

<simple_statement> ::= <expression> <assign_op> <expression>
                    | <expression> <post_op>
                    | <expression>
                    | <typ> <ident>
                    | <typ> <ident> "=" <expression>

<expression> ::= <simple_expression>
                | <memory_expression>

<memory_expression> ::= "*" <expression>
                    | "&" <expression>
                    | <expression> "[" <expression> "]"
                    | <expression> "." <ident>
                    | <expression> "->" <ident>

<simple_expression> ::= <expression> <binary_op> <expression>
                | <unary_op> <expression>
                | <ident> "(" <argument_list> ")"
                | <expression> "?" <expression> : <expression>
                | <ident>
                | <number>
 
<argument_list> ::= E | <expression> <argument_list>

; ---- Struct Stuff ----
<struct> ::= <struct_ident> ";"
			| <struct_ident> <struct_members> ";"

<struct_members> ::= "{" <struct_declarator_list> "}"

<struct_declarator_list> ::= E | <struct_declarator> <struct_declarator_list>

<struct_declarator> ::= <typ> <ident> ";"

<struct_ident> ::= "struct" <ident>

; ---- Operators ---- 
<post_op> ::= "++" | "--"
<binary_op> ::= "+" | "-" | "*" | "/" | "%" | "==" | "!=" | "<" | ">" | "<=" | ">=" | "&&" | "||" | "=" | "^" | "&" | "|" | "<<" | ">>"
<unary_op> ::= "-" | "~" | "!"
<assign_op> ::= "=" | "+=" | "-=" | "*=" | "/=" | "%=" | "<<=" | ">>=" | "&=" | "^="  "|="

; ---- Terminals ----
<ident> ::= ([a-z] [A-Z]) ([a-z] [A-Z] [0-9])*
<number> ::= ([0-9]) ([0-9])*
